Repository bellshade/Javascript, pull requests merged in 2021-10, with the labels that each got.

#52 Class js
  basic/010_classes/README.md
  basic/010_classes/classes.js
Labels: enhancement

#53 Menyederhanakan algoritma dan menambahkan sub materi operator
  basic/003_operator/README.md
  basic/003_operator/nullishCoalescingOperators.js
  data_structure/filterDuplicateArray.js
Labels: enhancement, algorithm

#55 docs: update readme & contributing docs
  CONTRIBUTING.md
  README.md
  basic/011_classes/README.md
  basic/011_classes/classes.js
  basic/README.md
  yarn.lock
Labels: documentation, enhancement

#59 Menambahkan algoritma email validation
  validation/emailValidation.js
Labels: enhancement

#62 fix: add switch case
  basic/005_conditioning/README.md
  basic/005_conditioning/conditionalStatements.js
Labels: documentation, enhancement

#64 add: menambahkan algoritma undirectedGraph
  data_structure/undirectedGraph.js
Labels: enhancement

#70 Menambahkan validasi IP Address
  validation/ipAddressValidation.js
Labels: documentation, enhancement

#65 Menambahkan validasi untuk cek No HP
  validation/phoneNumberValidation.js
Labels: documentation, enhancement

#66 Menambahkan sub materi operator
  basic/003_operator/README.md
  basic/003_operator/optionalChainingOperator.js
Labels: documentation, enhancement

#69 add: algoritma number to rupiah
  conversion/NumberToRupiah.js
Labels: documentation, enhancement

#63 add: menambahkan algoritma rot13 pada folder chiper
  cipher/rot13.js
Labels: enhancement

#67 Menambahkan typeOf
  basic/002_variable_datatype/README.md
  basic/002_variable_datatype/typeOf.js
Labels: documentation, enhancement

#82 feat: membuat folder 012_basic_program dan contoh algoritma
  basic/012_basic_program/getMean.js
  basic/012_basic_program/getMedian.js
  basic/012_basic_program/getMode.js
  other/getMedian.js
Labels: enhancement

#79 add: es6 dan isi foldernya
  es6/001_introduction/README.md
  es6/002_variable/README.md
  es6/002_variable/variable.js
  es6/003_arrow_function/README.md
  es6/003_arrow_function/arrowFunction.js
Labels: documentation, enhancement, help wanted

#92 feat: menambahkan pembahasan es6 tentang default parameter
  es6/005_default_parameter/README.md
  es6/005_default_parameter/defaultParameter.js
Labels: enhancement

#95 docs: menambahkan dokumentasi for of loop pada es6
  es6/005_for_of_loop/README.md
  es6/005_for_of_loop/forOfLoop.js
Labels: documentation

#182 feat: menambahkan automatic bot
  .mergify.yml
Labels: enhancement

#183 DOM: events
  learn/DOM/005_Events/README.md
  learn/DOM/005_Events/index.html
  learn/DOM/005_Events/script.js
Labels: DOM, javascript file, request tim javascript untuk review js file, html files, request tim javascript untuk review html file, markdown files, request docs team untuk review

#181 feat: menambahkan algoritma searchPrime
  algorithm/search/searchPrimeNumber.js
Labels: enhancement, algorithm, javascript file, request tim javascript untuk review js file, ready-to-merge
