Repository bellshade/Javascript, pull requests merged in 2021-12, with the labels that each got.

#238 docs: ubah alur belajar basic
  README.md
  learn/Basic/005_arithmetic_operation/README.md
  learn/Basic/005_arithmetic_operation/arithmeticOperation.js
  learn/Basic/006_looping/README.md
  learn/Basic/006_looping/break.js
  learn/Basic/006_looping/continue.js
  learn/Basic/006_looping/forWhileLoop.js
  learn/Basic/007_conditioning/README.md
  learn/Basic/007_conditioning/conditionalStatements.js
Labels: documentation, javascript file, markdown files, request tim javascript untuk review js file

#241 Menambahkan socket io sebagai dependensi dan menjalankan prettier
  algorithm/data_structure/chunkifyArray.js
  learn/Basic/008_function/functionAnonymous.js
  learn/Basic/008_function/functionCallback.js
  learn/DOM/006_Event_Listener/index.html
  learn/DOM/006_Event_Listener/script.js
  learn/DOM/008_Event_Bubbling_and_Capturing/script.js
  learn/DOM/009_Nodelist/index.html
  learn/DOM/009_Nodelist/script.js
  learn/OOP/005_Inheritance/inheritance.js
  package-lock.json
  package.json
  yarn.lock
Labels: javascript file, html files, ready-to-merge, request tim javascript untuk review js file, request tim javascript untuk review html file

#251 fix: memperbaiki navigasi badge yang salah
  server/utils/markdownParser.js
Labels: bug, javascript file, ready-to-merge, request tim javascript untuk review js file
