Repository bellshade/Javascript, pull requests merged in 2021-11, with the labels that each got.

#184 Menambahkan Materi DOM - Methods
  algorithm/conversion/HexToHsl.js
  algorithm/conversion/RomanToInteger.js
  algorithm/search/searchPrimeNumber.js
  learn/DOM/002_DOM_Nodes/nodes.js
  learn/DOM/003_Collections/script.js
  learn/DOM/004_Methods/README.md
  learn/DOM/004_Methods/img/classlist1.jpg
  learn/DOM/004_Methods/img/classlist2.jpg
  learn/DOM/004_Methods/img/classlist3.jpg
  learn/DOM/004_Methods/img/classlist4.jpg
  learn/DOM/004_Methods/img/classlist5.jpg
  learn/DOM/004_Methods/img/codesebelum.jpg
  learn/DOM/004_Methods/img/codesesudah.jpg
  learn/DOM/004_Methods/img/hasilcode.jpg
  learn/DOM/004_Methods/img/hasilpage.jpg
  learn/DOM/004_Methods/img/sebelum1.jpg
  learn/DOM/004_Methods/img/sebelum2.jpg
  learn/DOM/004_Methods/img/sebelumc2.jpg
  learn/DOM/004_Methods/img/sesudahc2.jpg
  learn/DOM/004_Methods/img/setattribut1.jpg
  learn/DOM/004_Methods/img/setattribut2.jpg
  learn/DOM/004_Methods/img/setattribute.jpg
  learn/DOM/004_Methods/img/settattribute3.jpg
  learn/DOM/004_Methods/img/style1.jpg
  learn/DOM/004_Methods/img/style2.jpg
  learn/DOM/004_Methods/img/style3.jpg
  learn/DOM/004_Methods/img/style4.jpg
  learn/DOM/004_Methods/index.html
  learn/DOM/004_Methods/script.js
  learn/DOM/005_Events/script.js
  learn/DOM/008_Traversal/script.js
  learn/Web_Api/GeoLocation/geolocation.js
Labels: javascript file, request JS team untuk review JS file, html files, request JS team untuk review HTML file, markdown files, request docs team untuk review, ready-to-merge, request tim javascript untuk review js file, request tim javascript untuk review html file

#189 feat: menambahkan algoritma vowelSort
  algorithm/sorting_algorithm/vowelSort.js
Labels: enhancement, javascript file, ready-to-merge, request tim javascript untuk review js file

#195 Menambahkan README pada folder Basic dan DOM
  learn/Basic/005_conditioning/README.md
  learn/Basic/005_conditioning/conditionalStatements.js
  learn/Basic/006_arithmetic_operation/README.md
  learn/Basic/006_arithmetic_operation/arithmeticOperation.js
  learn/Basic/015_basic_program/getMean.js
  learn/Basic/015_basic_program/getMedian.js
  learn/Basic/015_basic_program/getMode.js
  learn/Basic/015_basic_program/recursive.js
  learn/Basic/README.md
  learn/DOM/004_Methods/README.md
  learn/DOM/README.md
Labels: javascript file, markdown files, request docs team untuk review, ready-to-merge, request tim javascript untuk review js file

#197 Menambahkan materi anonymous function dan algoritma chunkifyArray
  algorithm/data_structure/chunkifyArray.js
  learn/Basic/008_function/README.md
  learn/Basic/008_function/functionAnonymous.js
  learn/Basic/008_function/functionCallback.js
Labels: javascript file, markdown files, request docs team untuk review, ready-to-merge, request tim javascript untuk review js file

#194 DOM Event Bubbling And Capturing
  algorithm/sorting/bubbleSort.js
  algorithm/sorting/countingSort.js
  algorithm/sorting/insertionSort.js
  algorithm/sorting/multiLevelSort.js
  algorithm/sorting/quickSort.js
  algorithm/sorting/sortPeopleName.js
  algorithm/sorting/vowelSort.js
  learn/DOM/004_Methods/script.js
  learn/DOM/007_Traversal/README.md
  learn/DOM/007_Traversal/index.html
  learn/DOM/008_Event_Bubbling_and_Capturing/README.md
  learn/DOM/008_Event_Bubbling_and_Capturing/img/anbub.gif
  learn/DOM/008_Event_Bubbling_and_Capturing/img/anbub.jpg
  learn/DOM/008_Event_Bubbling_and_Capturing/img/bub1.gif
  learn/DOM/008_Event_Bubbling_and_Capturing/img/bub2.jpg
  learn/DOM/008_Event_Bubbling_and_Capturing/img/cap.gif
  learn/DOM/008_Event_Bubbling_and_Capturing/img/cap.jpg
  learn/DOM/008_Event_Bubbling_and_Capturing/index.html
  learn/DOM/008_Event_Bubbling_and_Capturing/script.js
Labels: javascript file, html files, markdown files, request docs team untuk review, ready-to-merge, request tim javascript untuk review js file, request tim javascript untuk review html file

#198 docs: menambahkan materi DOM Event Listener
  learn/DOM/006_Event_Listener/README.md
  learn/DOM/006_Event_Listener/index.html
  learn/DOM/006_Event_Listener/script.js
Labels: documentation, javascript file, html files, markdown files, request docs team untuk review, ready-to-merge, request tim javascript untuk review js file, request tim javascript untuk review html file

#171 UI server, memperbarui script dan update hal kecil lainnya
  .eslintignore
  .github/CODEOWNERS
  .mergify.yml
  .tern-project
  CONTRIBUTING.md
  README.md
  learn/DOM/002_DOM_Nodes/index.html
  learn/DOM/003_Collections/index.html
  learn/DOM/004_Methods/index.html
  learn/DOM/005_Events/index.html
  learn/DOM/007_Traversal/index.html
  learn/DOM/008_Event_Bubbling_and_Capturing/index.html
  learn/WebApi/GeoLocation/index.html
  learn/WebApi/localStorage/index.html
  learn/WebApi/sessionStorage/index.html
  package-lock.json
  package.json
  server/app.js
  server/config/constant.js
  server/config/routingData.js
  server/controllers/common.js
  server/controllers/html.js
  server/controllers/index.js
  server/controllers/node.js
  server/controllers/socket.js
  server/plugins/routing.js
  server/plugins/socket.js
  server/plugins/static.js
  server/plugins/view.js
  server/public/css/htmlViewer.css
  server/public/css/markdown.css
  server/public/css/nodeViewer.css
  server/public/js/common.js
  server/public/js/htmlViewer.js
  server/public/js/nodeViewer.js
  server/utils/checker.js
  server/utils/directoryScanner.js
  server/utils/index.js
  server/utils/markdownParser.js
  server/views/common.ejs
  server/views/root.ejs
  server/views/runner/htmlViewer.ejs
  server/views/runner/nodeViewer.ejs
  yarn.lock
Labels: enhancement, javascript file, request JS team untuk review JS file, html files, request JS team untuk review HTML file, markdown files, request javascript team docs untuk review, request tim javascript untuk review js file, request tim javascript untuk review html file, request docs team untuk review

#199 docs: menambahkan nav di materi Basic
  learn/Basic/001_hello_world/README.md
  learn/Basic/002_variable_datatype/README.md
  learn/Basic/003_operator/README.md
  learn/Basic/004_string_and_string_manipulation/README.md
  learn/Basic/005_conditioning/README.md
  learn/Basic/006_arithmetic_operation/README.md
  learn/Basic/007_looping/README.md
  learn/Basic/008_function/README.md
  learn/Basic/009_array/README.md
  learn/Basic/010_array_manipulation/README.md
  learn/Basic/011_object/README.md
  learn/Basic/012_object_manipulation/README.md
  learn/Basic/013_classes/README.md
  learn/Basic/014_strict_mode/README.md
Labels: documentation, markdown files, request javascript team docs untuk review, ready-to-merge, request docs team untuk review

#211 fix: menambahkan kembali package yang sebelumnya diubah
  learn/Basic/005_conditioning/conditionalStatements.js
  learn/Basic/014_strict_mode/strictMode.js
  package-lock.json
  package.json
  server/public/js/common.js
  server/utils/markdownParser.js
  yarn.lock
Labels: bug, javascript file, ready-to-merge, request tim javascript untuk review js file

#217 docs: menambahkan nav di folder DOM dan ES6
  learn/DOM/001_Introduction/README.md
  learn/DOM/002_DOM_Nodes/README.md
  learn/DOM/003_Collections/README.md
  learn/DOM/004_Methods/README.md
  learn/DOM/005_Events/README.md
  learn/DOM/006_Event_Listener/README.md
  learn/DOM/007_Traversal/README.md
  learn/DOM/008_Event_Bubbling_and_Capturing/README.md
  learn/DOM/README.md
  learn/ES6/001_introduction/README.md
  learn/ES6/002_variable/README.md
  learn/ES6/003_arrow_function/README.md
  learn/ES6/004_template_literals/README.md
  learn/ES6/005_tagged_templates/README.md
  learn/ES6/006_destructuring_assignment/README.md
  learn/ES6/007_for_of_loop/README.md
  learn/ES6/008_spread_operator/README.md
  learn/ES6/009_function_rest_parameter/README.md
  learn/ES6/010_default_parameter/README.md
  learn/ES6/011_map_objects/README.md
  learn/ES6/012_string_includes/README.md
  learn/ES6/013_string_helpers/README.md
Labels: documentation, markdown files, ready-to-merge

#218 Menambahkan nav badge di Basic dan membuat Pengenalan OOP
  README.md
  learn/Basic/001_hello_world/README.md
  learn/Basic/002_variable_datatype/README.md
  learn/Basic/003_operator/README.md
  learn/Basic/004_string_and_string_manipulation/README.md
  learn/Basic/005_conditioning/README.md
  learn/Basic/006_arithmetic_operation/README.md
  learn/Basic/007_looping/README.md
  learn/Basic/008_function/README.md
  learn/Basic/009_array/README.md
  learn/Basic/010_array_manipulation/README.md
  learn/Basic/011_object/README.md
  learn/Basic/012_object_manipulation/README.md
  learn/Basic/013_classes/README.md
  learn/Basic/013_classes/classes.js
  learn/Basic/013_strict_mode/README.md
  learn/Basic/013_strict_mode/strictMode.js
  learn/Basic/014_basic_program/README.md
  learn/Basic/014_basic_program/getMean.js
  learn/Basic/014_basic_program/getMedian.js
  learn/Basic/014_basic_program/getMode.js
  learn/Basic/014_basic_program/recursive.js
  learn/Basic/README.md
  learn/OOP/001_Introduction/README.md
  learn/OOP/001_Introduction/class.js
Labels: javascript file, markdown files, ready-to-merge, request tim javascript untuk review js file

#228 add: menambahkan materi nodelist
  learn/DOM/008_Event_Bubbling_and_Capturing/README.md
  learn/DOM/009_Nodelist/README.MD
  learn/DOM/009_Nodelist/img/nodelist1.png
  learn/DOM/009_Nodelist/img/nodelist2.png
  learn/DOM/009_Nodelist/index.html
  learn/DOM/009_Nodelist/script.js
  learn/DOM/README.md
  package-lock.json
  yarn.lock
Labels: add, javascript file, html files, markdown files, request tim javascript untuk review js file, request tim javascript untuk review html file

#233 Menambahkan materi Inheritance
  learn/OOP/005_Inheritance/README.md
  learn/OOP/005_Inheritance/inheritance.js
Labels: javascript file, markdown files, request tim javascript untuk review js file
