Repository bellshade/Javascript, pull requests merged in 2022-05, with the labels that each got.

#308 docs: menambahkan cara setup ui server
  README.md
Labels: documentation, markdown files, ready-to-merge

#297 feat: menambahkan `@bellshade/ningali` sebagai ganti folder `server`
  .eslintrc.yml
  package-lock.json
  package.json
  pnpm-lock.yaml
  server/app.js
  server/config/constant.js
  server/config/routingData.js
  server/controllers/common.js
  server/controllers/html.js
  server/controllers/index.js
  server/controllers/node.js
  server/controllers/socket.js
  server/plugins/routing.js
  server/plugins/socket.js
  server/plugins/static.js
  server/plugins/view.js
  server/public/css/htmlViewer.css
  server/public/css/markdown.css
  server/public/css/nodeViewer.css
  server/public/js/common.js
  server/public/js/htmlViewer.js
  server/public/js/nodeViewer.js
  server/utils/checker.js
  server/utils/directoryScanner.js
  server/utils/index.js
  server/utils/markdownParser.js
  server/views/common.ejs
  server/views/root.ejs
  server/views/runner/htmlViewer.ejs
  server/views/runner/nodeViewer.ejs
  viewer.js
  yarn.lock
Labels: enhancement, javascript file, ready-to-merge, request tim javascript untuk review js file

#319 fix: mengignore peer deps popperjs yang tidak dipakai bootstrap
  package.json
Labels: bug, ready-to-merge
