Repository bellshade/Javascript, pull requests merged in 2022-02, with the labels that each got.

#270 Preparasi sebelum masuk materi OOP Intermediate
  learn/Basic/003_operator/doubleBangOperator.js
  learn/Basic/004_string_and_string_manipulation/README.md
  learn/Basic/005_arithmetic_operation/README.md
  learn/Basic/006_looping/README.md
  learn/Basic/007_conditioning/README.md
  learn/Basic/008_function/README.md
  learn/OOP/002_Object_Property_Method/example.js
  learn/OOP/Basic/001_Introduction/README.md
  learn/OOP/Basic/001_Introduction/class.js
  learn/OOP/Basic/002_Object_Property_Method/README.md
  learn/OOP/Basic/002_Object_Property_Method/example.js
  learn/OOP/Basic/003_Encapsulation/README.md
  learn/OOP/Basic/003_Encapsulation/encapsulation.js
  learn/OOP/Basic/004_Abstraction/README.md
  learn/OOP/Basic/004_Abstraction/abstraction.js
  learn/OOP/Basic/005_Inheritance/README.md
  learn/OOP/Basic/005_Inheritance/inheritance.js
  learn/OOP/Basic/006_Polymorphism/README.md
  learn/OOP/Basic/006_Polymorphism/polymorphism.js
Labels: javascript file, markdown files, ready-to-merge, request tim javascript untuk review js file

#274 Menambahkan materi Functional Programming
  learn/Functional/001_Introduction/README.md
  learn/Functional/001_Introduction/example.js
  learn/Functional/002_First_Class_Object/README.md
  learn/Functional/002_First_Class_Object/example.js
  learn/Functional/003_Pure_Function/README.md
  learn/Functional/003_Pure_Function/example.js
  learn/Functional/004_High_Order_Function/README.md
  learn/Functional/004_High_Order_Function/example.js
  learn/Functional/005_Composition/README.md
  learn/Functional/005_Composition/example.js
  learn/Functional/006_Immutability/README.md
  learn/Functional/006_Immutability/example.js
Labels: javascript file, markdown files, ready-to-merge, request tim javascript untuk review js file

#279 Menambahkan preview pembelajaran di folder `ES6` dan `WebApi`
  learn/Basic/README.md
  learn/DOM/README.md
  learn/ES6/README.md
  learn/WebApi/README.md
Labels: markdown files, ready-to-merge

#284 fix: memperbaiki issue dan deprecation message eslint
  .eslintrc.yml
  algorithm/search/data-test.json
  learn/ES6/011_map_objects/README.md
  learn/ES6/012_string_helpers/README.md
  learn/ES6/012_string_helpers/stringHelpers.js
  learn/ES6/012_string_includes/README.md
  learn/ES6/012_string_includes/stringIncludes.js
  learn/ES6/README.md
  learn/Functional/002_First_Class_Object/README.md
  learn/Functional/003_Pure_Function/README.md
  learn/Functional/004_High_Order_Function/README.md
  learn/Functional/005_Composition/README.md
Labels: bug, javascript file, html files, markdown files, ready-to-merge, request tim javascript untuk review js file, request tim javascript untuk review html file
