Repository bellshade/Javascript, pull requests merged in 2022-10, with the labels that each got.

#344 add: algoritma untuk deteksi ukuran window browser secara realtime
  algorithm/WebRelated/RealtimeWindowSizeDetection/detector.js
  algorithm/WebRelated/RealtimeWindowSizeDetection/index.html
Labels: add, javascript file, html files, ready-to-merge, request tim javascript untuk review js file, request tim javascript untuk review html file, HACKTOBERFEST-ACCEPTED

#343 docs: memperbaiki URL yang salah di contoh "Navbar"
  README.md
Labels: documentation, markdown files, ready-to-merge

#348 feat: algoritma untuk menemukan faktor faktor dari suatu bilangan
  algorithm/math/factorTree.js
Labels: enhancement, javascript file, ready-to-merge, request tim javascript untuk review js file, HACKTOBERFEST-ACCEPTED

#346 add: program hitung jumlah kata dan karakter secara realtime
  algorithm/WebRelated/WordsAndCharsCounter/counter.js
  algorithm/WebRelated/WordsAndCharsCounter/index.html
Labels: Ok to merge, add, javascript file, html files, ready-to-merge, request tim javascript untuk review js file, request tim javascript untuk review html file, HACKTOBERFEST-ACCEPTED

#340 feat: menambahkan fungsi agar teks tidak bisa di-copy
  algorithm/WebRelated/preventCopy/index.html
  algorithm/WebRelated/preventCopy/prevent.js
Labels: enhancement, javascript file, html files, ready-to-merge, request tim javascript untuk review js file, request tim javascript untuk review html file, HACKTOBERFEST-ACCEPTED

#350 feat: menambahkan algoritma penyingkatan nama
  algorithm/other/nameShortener.js
Labels: Ok to merge, enhancement, javascript file, ready-to-merge, request tim javascript untuk review js file

#351 add: array manipulation - findIndex
  learn/Basic/010_array_manipulation/README.md
  learn/Basic/010_array_manipulation/every.js
  learn/Basic/010_array_manipulation/findIndex.js
Labels: add, javascript file, markdown files, ready-to-merge, request tim javascript untuk review js file, HACKTOBERFEST-ACCEPTED

#354 fix: visitor badge
  README.md
Labels: bug, markdown files, ready-to-merge, HACKTOBERFEST-ACCEPTED
