Repository bellshade/Javascript, pull requests merged in 2023-10, with the labels that each got.

#393 feat: materi WebApi Fetch
  learn/WebApi/fetch/README.md
  learn/WebApi/fetch/fetch.js
  learn/WebApi/fetch/index.html
Labels: javascript file, html files, markdown files, ready-to-merge, request tim javascript untuk review js file, request tim javascript untuk review html file, HACKTOBERFEST-ACCEPTED

#396 add: menambahkan algoritma baru
  algorithm/other/terbilang.js
Labels: javascript file, ready-to-merge, request tim javascript untuk review js file, HACKTOBERFEST-ACCEPTED

#395 docs: menambahkan dan mengubah dokumentasi
  learn/Basic/003_operator/README.md
  learn/Basic/006_looping/README.md
  learn/Basic/009_array/README.md
Labels: markdown files, ready-to-merge, HACKTOBERFEST-ACCEPTED
